# http://about.travis-ci.org/docs/user/languages/php/
language: php

php:
    - "5.5"
    - "5.6"
    - nightly

before_install:
    - composer --no-interaction self-update

install:
    - composer --prefer-source --no-interaction install

script:
    - vendor/bin/phpspec run -v

notifications:
    irc: "irc.freenode.org#wykopaspiestats"
